from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from tierproxy.async_client import AsyncTierProxy
    from tierproxy.client import TierProxy


class Tunnel(BaseModel):
    """Single CONNECT tunnel record.

    The ``/v1/usage/recent`` endpoint returns the most recent 100 tunnel
    records for the authenticated account. Use for forensic debugging of
    failed scrapes — correlate ``target_host``, ``status_code``, and
    ``duration_ms`` to identify upstream or target-side issues.
    """

    client_id: str = Field(
        default="",
        description=(
            "Account identifier that originated the tunnel. May be empty when the"
            " record predates per-tunnel client tagging. Matches :attr:`Me.client_id`."
        ),
    )
    upstream_id: str = Field(
        description=(
            "Upstream provider that handled the tunnel (e.g. 'decodo', 'iproyal')."
            " Useful for attributing failures to a specific provider."
        )
    )
    target_host: str = Field(
        description=(
            "``host:port`` of the CONNECT target (e.g. 'example.com:443')."
            " Derived from the client's CONNECT request line."
        )
    )
    bytes_up: int = Field(
        description=(
            "Bytes sent from the client toward the upstream (request bodies, headers)"
            " during this tunnel."
        )
    )
    bytes_down: int = Field(
        description=(
            "Bytes received by the client from the upstream (response bodies, headers)"
            " during this tunnel."
        )
    )
    cost_usd: float = Field(
        description=(
            "Estimated cost in USD for this tunnel's traffic, based on the upstream's"
            " per-GB rate. Informational."
        )
    )
    duration_ms: int = Field(
        description=(
            "Total tunnel lifetime in milliseconds, from CONNECT accepted to both"
            " sides closed. Includes target connection time."
        )
    )
    timestamp: str = Field(
        description=(
            "ISO-8601 UTC timestamp when the tunnel was initiated (e.g. '2026-05-18T12:00:00Z')."
        )
    )
    status_code: int = Field(
        description=(
            "HTTP status code returned by the upstream in response to the CONNECT"
            " request. 200 means the tunnel was established successfully. Non-200"
            " (e.g. 407, 503) indicates the upstream rejected the connection."
        )
    )


class UsageRecent(BaseModel):
    """Envelope returned by ``/v1/usage/recent``.

    Contains the most recent tunnel records (up to 100) for the authenticated
    account, ordered from most recent to oldest. Access via
    :meth:`UsageRecentResource.get`.
    """

    tunnels: list[Tunnel] = Field(
        description=(
            "List of recent tunnel records, newest first. At most 100 entries."
            " Empty list means no tunnels have been recorded yet."
        )
    )
    ts: str = Field(
        description=(
            "ISO-8601 UTC timestamp when this snapshot was generated by the server"
            " (e.g. '2026-05-18T12:00:05Z'). Use to detect stale responses when"
            " polling."
        )
    )


class UsageRecentResource:
    """Recent-tunnels endpoint. Access via ``client.usage_recent``.

    Returns the last 100 CONNECT tunnel records for the account. Intended for
    forensic debugging: correlate ``target_host``, ``upstream_id``, and
    ``status_code`` to diagnose failed scrapes.
    """

    def __init__(self, client: TierProxy) -> None:
        self._client = client

    def get(self) -> UsageRecent:
        """Fetch the most recent tunnel records for the authenticated account.

        Returns:
            A :class:`UsageRecent` envelope containing up to 100
            :class:`Tunnel` records, newest first.

        Raises:
            AuthenticationError: API key invalid or revoked (HTTP 401).
            ServerError: Gateway internal error (HTTP 5xx).

        Example:
            >>> with TierProxy() as g:  # doctest: +SKIP
            ...     recent = g.usage_recent.get()
            ...     failed = [t for t in recent.tunnels if t.status_code != 200]
            ...     print(f"{len(failed)} failed tunnels in last 100")
        """
        data = self._client._transport.request("GET", "/v1/usage/recent")
        return UsageRecent.model_validate(data)


class AsyncUsageRecentResource:
    """Async variant of :class:`UsageRecentResource`. Access via ``async_client.usage_recent``."""

    def __init__(self, client: AsyncTierProxy) -> None:
        self._client = client

    async def get(self) -> UsageRecent:
        """Fetch the most recent tunnel records. See :meth:`UsageRecentResource.get`."""
        data = await self._client._transport.arequest("GET", "/v1/usage/recent")
        return UsageRecent.model_validate(data)
