#!/usr/bin/env bash
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
SPEC="${SPEC:-$ROOT/openapi/tierproxy.v1.yaml}"
OUT="$ROOT/sdks/python/src/tierproxy/_generated"

# Validate first
pipx run openapi-spec-validator "$SPEC"

rm -rf "$OUT.tmp" "$OUT"
pipx run --spec "openapi-python-client>=0.20" openapi-python-client generate \
  --path "$SPEC" \
  --output-path "$OUT.tmp" \
  --config "$ROOT/sdks/python/codegen.config.yaml" \
  --overwrite

# Keep only models — we already hand-write the resources.
mkdir -p "$OUT"
touch "$OUT/__init__.py"
cp -r "$OUT.tmp"/*/models "$OUT/models"

# Stamp do-not-edit banner.
for f in $(find "$OUT" -name "*.py"); do
  if ! head -1 "$f" | grep -q "# AUTOGENERATED"; then
    sed -i '1i# AUTOGENERATED FROM openapi/tierproxy.v1.yaml — DO NOT EDIT BY HAND' "$f"
  fi
done

rm -rf "$OUT.tmp"
echo "Codegen complete. Run pytest to verify."
